/run/initialize
/G4MuLE/runaction/plateid 0
/G4MuLE/runaction/energy 0.5 keV
/G4MuLE/runaction/angle_x 0.0 deg
/G4MuLE/runaction/angle_y 0.0 deg
/random/setSeeds 1 10
/G4MuLE/runaction/outputname test.txt
/run/beamOn 10000


/G4MuLE/runaction/plateid 0
/G4MuLE/runaction/energy 1.9 keV
/G4MuLE/runaction/angle_x 0.0 deg
/G4MuLE/runaction/angle_y 0.0 deg
/random/setSeeds 10 10
/G4MuLE/runaction/outputname test2.txt
/run/beamOn 10000
